### ISSUE TITLE
uninitialized constant CheckSftp::Timeout error

### ISSUE THREAD

**Issue by nadx969** [sensu-plugins/sensu-plugins-sftp#2]
when running the check on RHEL 7, seeing the following error

`/opt/sensu/embedded/bin/ruby /opt/sensu/embedded/bin/check-sftp.rb -h localhost -u USER -s PASSWORD -P 22 -t 30`
`CheckSftp OK`
`Check failed to run: uninitialized constant CheckSftp::Timeout, ["/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugins-sftp-0.0.2/bin/check-sftp.rb:107:in `rescue in run'", "/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugins-sftp-0.0.2/bin/check-sftp.rb:100:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"]`

let me if you need any additional details to help trouble shoot

**Comment by r0b0tAnthony** [comment]
I am having the same error on Ubuntu 14.04. Using embedded ruby.

**Comment by r0b0tAnthony** [comment]
Hey, I seemed to have fixed it. I removed the catch for Timeout::Error as that can be caught by the general exception catch/rescue. I also add a rescue for Connected Refused.

`class CheckSftp < Sensu::Plugin::Check::CLI
  option :host,
         short: '-h HOST',
         long: '--host HOST',
         description: 'Sftp Host',
         required: true

  option :port,
         short: '-P PORT',
         long: '--port PORT',
         description: 'Sftp Port',
         proc: proc(&:to_i),
         default: 22

  option :username,
         short: '-u USERNAME',
         long: '--user USERNAME',
         description: 'Sftp Username',
         required: true

  option :password,
         short: '-s PASSWORD',
         long: '--pass PASSWORD',
         description: 'Sftp Password',
         default: '',
         required: true

  option :timeout,
         short: '-t TIMEOUT',
         long: '--timeout TIMEOUT',
         proc: proc(&:to_i),
         description: 'Sftp Timeout',
         default: 60

  option :directory,
         short: '-d DIRECTORY',
         long: '--directory DIRECTORY',
         description: 'Directory to use for file checks',
         default: '/'

  option :match,
         short: '-m MATCH',
         long: '--match MATCH',
         description: 'Match files with this pattern for counting/file aging checks (*_, *_/*).'

  option :check_prefix,
         short: '-x PREFIX',
         description: 'Prefix for temporary file write check. Blank for none.'

  option :check_count,
         short: '-n COUNT',
         long: '--number COUNT',
         proc: proc(&:to_i),
         description: 'Alert if files > COUNT in directory'

  option :check_older,
         short: '-o OLDER_THAN',
         long: '--older_than OLDER_THAN',
         proc: proc(&:to_i),
         description: 'Alert if any file age > OLDER_THAN seconds'
  def run
    begin
      if sftp
        check_file_write
        check_file_count
        check_file_age
      end
    rescue SocketError => e
      critical "Could not connect: #{e.inspect}"
    rescue Net::SSH::AuthenticationFailed
      critical "Failed authentication with #{config[:username]}"
    rescue Net::SFTP::StatusException => e
      critical "SFTP Error - #{e.message}"
    rescue Errno::ECONNREFUSED
      critical "Failed to connect as conneciton was refused."
    rescue Exception => e
      critical "Unexpected error; #{e.inspect}"
    else
      ok
    end
  end

  private

  def check_file_write
    # #YELLOW
    if config[:check_prefix] # rubocop:disable GuardClause
      io = StringIO.new('Generated from Sensu at ' + Time.now.to_s)
      remote_path = File.join('', config[:directory], config[:check_prefix] + "_#{Time.now.to_i}.txt")
      sftp.upload!(io, remote_path)
      sftp.remove!(remote_path)
    end
  end

  def check_file_count
    # #YELLOW
    if config[:check_count] # rubocop:disable GuardClause
      critical "Too many files - #{config[:directory]} has #{matching_files.count} matching files" if matching_files.count > config[:check_count]
    end
  end

  def check_file_age
    # #YELLOW
    if config[:check_older]  # rubocop:disable GuardClause
      run_at    = Time.now
      old_files = matching_files.select { |f| (run_at.to_i - f.attributes.mtime) > config[:check_older] }
      unless old_files.empty?
        critical "Files too old - #{config[:directory]} has #{old_files.count} matching files older than #{config[:check_older]}s"
      end
    end
  end

  def matching_files
    @matching_files ||= sftp.dir.glob(config[:directory], config[:match]).select { |f| f.attributes.file? }
  end

  def sftp
    @sftp ||= Net::SFTP.start(config[:host], config[:username], password: config[:password], timeout: config[:timeout], port: config[:port])
  end
end
`

**Comment by r0b0tAnthony** [comment]
`meow`

**Comment by analytically** [comment]
Please submit a PR.

**Comment by nickpetrovic** [comment]
+1

**Comment by nickpetrovic** [comment]
Removed the timeout exception. Builds passed except for Ruby 1.9. I think thats beyond the scope of this issue.

`Gem::InstallError: net-ssh requires Ruby version >= 2.0.`
